G_map/G_map/urls.py
from django.contrib import admin
from django.urls import path,include
from G_map_registration import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Login.as_view(),name='Login' ),
    path('menus/',include('G_map_main_menus.urls')),

]

G_map/G_map_main_menus/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *

urlpatterns = [
    path('',index_menu.as_view(),name='menus' ),
    path('dashboard',dashboard.as_view(),name='dashboard' ),

# Roles path
    path('roles-view/',include([
        path('',Roles_View.as_view(),name='roles_view' ),
        path('edit-roles/<str:slug>',EditRoles_View.as_view(),name='edit_roles' ),
        path('actions-roles',RolesAction_View.as_view(),name='actions_roles' ),
        # permissions
        path('set-permissions/<str:slug>',SetPermissions_View.as_view(),name='set_permissions' ),
    ])),

# service path
    path('service-type/',include([
        path('',Service_TypeView.as_view(),name='service_type' ),
        path('add-service-type',AddService_TypeView.as_view(),name='add_service_type' ),
        path('edit-service-type/<str:slug>',EditService_TypeView.as_view(),name='edit_service_type' ),
        path('view-service-type/<str:slug>',ViewService_TypeView.as_view(),name='view_service_type' ),
        path('actions-service-type',ServiceTypeAction_View.as_view(),name='actions_servicetype' ),
    ])),

# department path
    path('Department/',include([
        path('',DepartmentView.as_view(),name='department' ),
        path('add-department',Add_DepartmentView.as_view(),name='add_department' ),
        path('edit-department/<str:slug>',Edit_DepartmentView.as_view(),name='edit_department' ),
        # path('view-department/<int:pk>',ViewService_TypeView.as_view(),name='view_department' ),
        path('actions-department',DepartmentAction_View.as_view(),name='actions_department' ),
    ])),

# designation path
    path('Designation/',include([
        path('',DesignationView.as_view(),name='designation' ),
        path('add-designation',Add_DesignationView.as_view(),name='add_designation' ),
        path('edit-designation/<str:slug>',Edit_DesignationView.as_view(),name='edit_designation' ),
        path('assign-department/<str:slug>',Assign_DepartmentView.as_view(),name='assign_department' ),
        path('actions-designation',DesignationAction_View.as_view(),name='actions_designation' ),
        
    ])),
# vendor path
    path('Vendor/',include([
        path('',VendorView.as_view(),name='vendor' ),
        path('add-vendor',Add_VendorView.as_view(),name='add_vendor' ),
        path('edit-vendor/<str:slug>',Edit_VendorView.as_view(),name='edit_vendor' ),
        path('actions-vendor',VendorAction_View.as_view(),name='actions_vendor' ),
        
    ])),
# questionnair path
    path('Questionnair/',include([
        path('',QuestionnairView.as_view(),name='questionnair' ),
        path('add-questionnair',Add_QuestionnairView.as_view(),name='add_questionnair' ),
        path('edit-vendor/<str:slug>',Edit_VendorView.as_view(),name='edit_vendor' ),
        path('actions-vendor',VendorAction_View.as_view(),name='actions_vendor' ),
        
    ])),

]

G_map/G_map_main_menus/models.py
from django.db import models
from django.contrib.auth.models import Group
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_lifecycle import LifecycleModelMixin, hook, AFTER_CREATE,AFTER_UPDATE,AFTER_SAVE

# Create your models here.
# class Company_Model(models.Model):
#     company_name = models.CharField(max_length=100)
#     address = models.TextField()
#     company_registrationNo = models.CharField(max_length=100)
#     company_registrationExpiry = models.DateField()
#     municipality_registration = models.CharField(max_length=100)
#     municipality_licenceExpiry = models.DateField()
#     chamber_of_commerceExpiry = models.DateField()
#     tax_registationExpiry = models.DateField()
#     vat_registationExpiry = models.DateField()
#     rent_for_needsExpiry = models.DateField()
#     professional_indemnityInsurance = models.CharField(max_length=256)
#     workman_compensationInsurance = models.CharField(max_length=256)
#     JSRS = models


class Service_Type_Model(models.Model):
    slug_field = models.SlugField(max_length=256,blank=True)
    service = models.CharField(max_length=100)
    status = models.CharField(max_length=180,choices=(
                ('Active','Active'),
                ('Inactive','Inactive')
            ),default='Active')
    scope_of_work = models.TextField()

    @receiver(post_save, sender='G_map_main_menus.Service_Type_Model')
    def save_slug(sender, *args, **kwargs):
        instance = Service_Type_Model.objects.filter(pk=kwargs['instance'].id)
        value = str(instance.first().service)+" "+str(instance.first().id)
        slug_field = slugify(value, allow_unicode=True)
        instance.update(slug_field=slug_field)

    def __str__(self):
        return self.service
        

    
Group.add_to_class(
    'status', models.CharField(max_length=180,choices=(
        ('Active','Active'),
        ('Inactive','Inactive')
        ),default='Active'),
    
    
    )
Group.add_to_class(
    'slug_field' , models.SlugField(max_length=256,blank=True)
)
@receiver(post_save, sender=Group)
def save_slug(sender, *args, **kwargs):
    instance = Group.objects.filter(pk=kwargs['instance'].id)
    value = str(instance.first().name)+" "+str(instance.first().id)
    slug_field = slugify(value, allow_unicode=True)
    instance.update(slug_field=slug_field)

class Department_Model(LifecycleModelMixin,models.Model):
    slug_field = models.SlugField(max_length=256,blank=True)
    department_name = models.CharField(max_length=100)
    service_type = models.ForeignKey(Service_Type_Model,on_delete=models.CASCADE)
    status = models.CharField(max_length=180,choices=(
                ('Active','Active'),
                ('Inactive','Inactive')
            ),default='Active')
    
    class Meta:
        db_table = 'department'

    def __str__(self):
        return self.department_name

    @receiver(post_save, sender='G_map_main_menus.Department_Model')
    def save_slug(sender, *args, **kwargs):
        instance = Department_Model.objects.filter(pk=kwargs['instance'].id)
        value = str(instance.first().department_name)+" "+str(instance.first().id)
        slug_field = slugify(value, allow_unicode=True)
        instance.update(slug_field=slug_field)

class Designation_Model(models.Model):
    slug_field = models.SlugField(max_length=256,blank=True)
    designation = models.CharField(max_length=100)
    department = models.ManyToManyField(Department_Model,blank=True)
    status = models.CharField(max_length=180,choices=(
                ('Active','Active'),
                ('Inactive','Inactive')
            ),default='Active')

    @receiver(post_save, sender='G_map_main_menus.Designation_Model')
    def save_slug(sender, *args, **kwargs):
        instance = Designation_Model.objects.filter(pk=kwargs['instance'].id)
        value = str(instance.first().designation)+" "+str(instance.first().id)
        slug_field = slugify(value, allow_unicode=True)
        instance.update(slug_field=slug_field)

class Vendor_Model(models.Model):
    slug_field = models.SlugField(max_length=150,blank=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    status = models.CharField(max_length=180,choices=(
                ('Active','Active'),
                ('Inactive','Inactive')
            ),default='Active')

    @receiver(post_save, sender='G_map_main_menus.Vendor_Model')
    def save_slug(sender, *args, **kwargs):
        instance = Vendor_Model.objects.filter(pk=kwargs['instance'].id)
        value = str(instance.first().name)+" "+str(instance.first().id)
        slug_field = slugify(value, allow_unicode=True)
        instance.update(slug_field=slug_field)

class Questionnair_Model(models.Model):
    service_type = models.ForeignKey(Service_Type_Model,on_delete=models.CASCADE)
    question = models.TextField()
    status = models.CharField(max_length=180,choices=(
                ('Active','Active'),
                ('Inactive','Inactive')
            ),default='Active')

G_map/G_map_main_menus/forms.py
from pyexpat import model
from django.contrib.auth.models import Group
from django import forms
from .models import *
from ckeditor.widgets import CKEditorWidget
from django.forms import inlineformset_factory



class RolesForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ("__all__")

    def __init__(self, *args, **kwargs):
        super(RolesForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({'class':'form-control form-control-sm'})
    
    

    @receiver(post_save, sender=Group)
    def save_slug(sender, *args, **kwargs):
        print(sender,"ssss")
        instance = Group.objects.filter(pk=kwargs['instance'].id)
        value = str(instance.first().name)+" "+str(instance.first().id)
        slug_field = slugify(value, allow_unicode=True)
        instance.update(slug_field=slug_field)

class Service_TypeForm(forms.ModelForm):
    class Meta:
        model = Service_Type_Model
        fields = ("__all__")

    def __init__(self, *args, **kwargs):
        super(Service_TypeForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({'class':'form-control form-control-sm'})
        self.fields['scope_of_work'].widget = CKEditorWidget() 

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department_Model
        fields = ("__all__")

    def __init__(self, *args, **kwargs):
        super(DepartmentForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({'class':'form-control form-control-sm'})

class DesignationForm(forms.ModelForm):
    class Meta:
        model = Designation_Model
        fields = ("__all__")

    def __init__(self, *args, **kwargs):
        super(DesignationForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({'class':'form-control form-control-sm'})

class AssignDepartmentForm(forms.ModelForm):
    class Meta:
        model = Designation_Model
        fields = ("designation","department")

    def __init__(self, *args, **kwargs):
        super(AssignDepartmentForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({'class':'form-control form-control-sm'})

class VendorForm(forms.ModelForm):
    class Meta:
        model = Vendor_Model
        fields = ("__all__")

    def __init__(self, *args, **kwargs):
        super(VendorForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({'class':'form-control form-control-sm'})


class QuestionnairForm(forms.ModelForm):
    class Meta:
        model = Questionnair_Model
        fields = ("__all__")

    def __init__(self, *args, **kwargs):
        super(QuestionnairForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({'class':'form-control form-control-sm'})

class DionamicQuestionForm(forms.ModelForm):
    class Meta:
        model = Questionnair_Model
        fields = ("question",)

    def __init__(self, *args, **kwargs):
        super(DionamicQuestionForm, self).__init__(*args, **kwargs)
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({'class':'form-control form-control-sm'})

G_map/G_map_main_menus/templates/roles/edit_roles.html
{% extends 'main.html' %}
{% block title %}Edit Roles{% endblock title %}
{% block content %}
<div class="page-header">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h4>Roles</h4>
            </div>
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{{ request.META.HTTP_REFERER }}">Back</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Edit Roles
                    </li>
                </ol>
            </nav>
        </div>
        
    </div>
</div>
<div class="card pd-20 card-box mb-30">
    
    
    <form method="post">
        {% csrf_token %}
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Role Name</label>
                        {{form.name}}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Status</label>
                        <select name="status" class="form-control form-control-sm" id="id_status" disabled>
                            <option value="Active" {% if form.status.value == 'Active' %}selected{% endif %}>Active</option>
                          
                            <option value="Inactive" {% if form.status.value == 'Inactive' %}selected{% endif %}>Inactive</option>
                          
                          </select>
                        {{form.status.as_hidden}}
                        
                    </div>
                </div>
                
            </div>
        </div>
        
    
    <div class="card-footer" style="background-color:#fff;">
        <div class="form-group" >
            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-danger btn-sm" style="float: left;">Cancel</a>
            <button type="submit" class="btn btn-secondary btn-sm" style="float: right;">Submit</button>
        </div>
        
    </div>
    </form>
</div>
{% endblock content %}

G_map/G_map_main_menus/templates/roles/roles_page.html
{% extends 'main.html' %}
{% block title %}Roles{% endblock title %}
{% block content %}

    <div class="min-height-200px">
        {% include 'messages.html' %}
        <div class="page-header">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="title">
                        <h4>Roles</h4>
                    </div>
                    <nav aria-label="breadcrumb" role="navigation">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ request.META.HTTP_REFERER }}">Back</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">
                                Roles
                            </li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right">
                    <div class="dropdown">
                        <a
                            class="btn btn-primary dropdown-toggle"
                            href="#"
                            role="button"
                            data-toggle="dropdown"
                        >
                            January 2018
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="#">Export List</a>
                            <a class="dropdown-item" href="#">Policies</a>
                            <a class="dropdown-item" href="#">View Assets</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card pd-20 card-box mb-30">
            <div class=" clearfix">
                <div class="pull-left">
                    <h4 class="text-blue h4">Add Roles</h4>
                   
                </div>
            </div>
            <form class="card-body" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Role Name</label>
                            {{forms.name}}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>{{forms.status.label}}</label>
                            <select name="status" class="form-control form-control-sm" id="id_status" disabled>
                                <option value="Active" selected="">Active</option>
                              
                                <option value="Inactive">Inactive</option>
                              
                              </select>
                            {{forms.status.as_hidden}}
                            
                        </div>
                    </div>
                    
                </div>
            
            <div class="card-footer" style="background-color:#fff;">
                <div class="form-group" >
                    <button type="submit" class="btn btn-secondary btn-sm" style="float: right;">Submit</button>
                </div>
                
            </div>
            </form>
        </div>
                    
        <!-- Export Datatable start -->
        <div class="card-box mb-30">
            <div class="pd-20">
          
            </div>
            <div class="pb-20">
                <table
                    class="table hover multiple-select-row data-table-export nowrap"
                >
                    <thead>
                        <tr>
                            <th class="table-plus datatable-nosort" style="width: 10%;">Sl no</th>
                            <th style="width: 30%;">Role name</th>
                            <th style="width: 20%;">Status</th>
                            <th style="width: 40%;text-align: center;">Actions</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in data %}
                        <tr>
                            <td class="table-plus" style="width: 10%;">{{forloop.counter}}</td>
                            <td style="width: 30%;">{{i.name}}</td>
                            <td style="width: 20%;"><span class="badge badge-{% if i.status == 'Active' %}success{% else %}danger{% endif %}">{{i.status}}</span></td>
                            <td style="width: 40%;">
                               {% if i.status == 'Active' %}
                                <button type="button" class="btn btn-outline-secondary btn-sm disable_btn" style="float: right;" data-toggle="modal" data-id="{{i.id}}"
                                data-target="#confirmation-modal-disable">Disable</button>
                               {% else %}
                                <button type="button" class="btn btn-outline-secondary btn-sm enable_btn" style="float: right;" data-toggle="modal" data-id="{{i.id}}"
                                data-target="#confirmation-modal-enable">Enable</button>
                              {% endif %}
                                <a href="{% url 'edit_roles' i.slug_field %}" class="btn btn-outline-secondary btn-sm mr-2" style="float: right;">Edit</a>
                                <a href="{% url 'set_permissions' i.slug_field %}" class="btn btn-secondary btn-sm mr-2" style="float: right;">Set permission</a>
                                
                            </td>
                            
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- Export Datatable End -->
    </div>
    
         
           
            <div
                class="modal fade"
                id="confirmation-modal-enable"
                tabindex="-1"
                role="dialog"
                aria-hidden="true"
            >
                <div
                    class="modal-dialog modal-dialog-centered"
                    role="document"
                >
                    <div class="modal-content">
                        <form method="post" action="{% url 'actions_roles' %}">
                            {% csrf_token %}
                            <div class="modal-body text-center font-18">
                                <h4 class="padding-top-30 mb-30 weight-500">
                                    Are you sure you want to enable?
                                    <input hidden type="text" name="disable_data" id="enable_divcont">
                                </h4>
                                <div
                                    class="padding-bottom-30 row"
                                    style="max-width: 170px; margin: 0 auto"
                                >
                                    <div class="col-6">
                                        <button
                                            type="button"
                                            class="btn btn-secondary border-radius-100 btn-block confirmation-btn"
                                            data-dismiss="modal"
                                        >
                                            <i class="fa fa-times"></i>
                                        </button>
                                        NO
                                    </div>
                                    <div class="col-6">
                                        <button
                                            type="submit"
                                            class="btn btn-primary border-radius-100 btn-block confirmation-btn"
                                            
                                        >
                                            <i class="fa fa-check"></i>
                                        </button>
                                        YES
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
       
    
  
        
            
           
            <div
                class="modal fade"
                id="confirmation-modal-disable"
                tabindex="-1"
                role="dialog"
                aria-hidden="true"
            >
                <div
                    class="modal-dialog modal-dialog-centered"
                    role="document"
                >
                    <div class="modal-content">
                        <form method="post" action="{% url 'actions_roles' %}">
                            {% csrf_token %}
                            <div class="modal-body text-center font-18">
                                <h4 class="padding-top-30 mb-30 weight-500">
                                    Are you sure you want to disable?
                                    <input hidden type="text" id="disable_divcont" name="disable_data">
                                </h4>
                                <div
                                    class="padding-bottom-30 row"
                                    style="max-width: 170px; margin: 0 auto"
                                >
                                    <div class="col-6">
                                        <button
                                            type="button"
                                            class="btn btn-secondary border-radius-100 btn-block confirmation-btn"
                                            data-dismiss="modal"
                                        >
                                            <i class="fa fa-times"></i>
                                        </button>
                                        NO
                                    </div>
                                    <div class="col-6">
                                        <button
                                            type="submit"
                                            class="btn btn-primary border-radius-100 btn-block confirmation-btn"
                                           
                                        >
                                            <i class="fa fa-check"></i>
                                        </button>
                                        YES
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
      
            

<script>
    $('.disable_btn').click(function(){
        var x_id = $(this).attr('data-id')
        $('#disable_divcont').val(x_id)
    })
    $('.enable_btn').click(function(){
        var x_id = $(this).attr('data-id')
        $('#enable_divcont').val(x_id)
    })
</script>
{% endblock content %}